w<-read.table("household_power_consumption.txt",header=TRUE,sep=";",skip=66636,nrows=2879,na.strings="?")
names(w)<-names(colnames<-read.table("household_power_consumption.txt",header=TRUE,nrows=1,na.strings="?",sep=";"))
png("Plot4.png",width = 480, height = 480)
par(mfrow=c(2,2))
  plot(w$Global_active_power,ylab="Global Active Power",xlab="",type="l",xaxt="n")
    axis(1,labels=c("Thu","Fri","Sat"),at=c(0,1441,2879))
  plot(w$Voltage,ylab="Voltage",xlab="datetime",type="l",xaxt="n")
    axis(1,labels=c("Thu","Fri","Sat"),at=c(0,1441,2879))
  plot(w$Sub_metering_1,type="l",ylab="Energy sub metering",xlab="",xaxt="n")
    lines(w$Sub_metering_2,col="red")
    lines(w$Sub_metering_3,col="blue")
    legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=1,bty="n")
    axis(1,labels=c("Thu","Fri","Sat"),at=c(0,1441,2879))
  plot(w$Global_reactive_power,ylab="Global_reactive_power",xlab="datetime",type="l",xaxt="n")
    axis(1,labels=c("Thu","Fri","Sat"),at=c(0,1441,2879))
dev.off()