w<-read.table("household_power_consumption.txt",header=TRUE,sep=";",skip=66636,nrows=2879,na.strings="?")
names(w)<-names(colnames<-read.table("household_power_consumption.txt",header=TRUE,nrows=1,na.strings="?",sep=";"))
png("Plot3.png",width = 480, height = 480)
plot(w$Sub_metering_1,type="l",ylab="Energy sub metering",xlab="",xaxt="n")
 lines(w$Sub_metering_2,col="red")
 lines(w$Sub_metering_3,col="blue")
 legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=1)
 axis(1,labels=c("Thu","Fri","Sat"),at=c(0,1441,2879))
dev.off()